import React, { Component } from 'react';
import { View, Text, Button, Image, DeviceEventEmitter, ToolbarAndroid } from 'react-native';
import RNAudioStreamer from 'react-native-audio-streamer';
import style from '../../themes/styles/musicPlayerStyle';
import Entypo from 'react-native-vector-icons/Entypo';
import Slider from 'react-native-slider';
import { IMAGE_HOST_URL } from '../../config/settings';
import images from '../../themes/settings/images';
import _ from 'lodash';
import PushNotification from 'react-native-push-notification';
import { store } from '../libraries/behaviour';

var listener = true;

class MusicPlayerScreen extends Component {
	static navigationOptions = {
	   header: null
	};

	constructor(props) {
		super(props);
		const { state } = this.props.navigation;

		this.state = {
			songPlaying: state.params.current,
			status: 1,
			duration: 0,
			user: state.params.user
		}
		RNAudioStreamer.setUrl(encodeURI(`${IMAGE_HOST_URL}/${this.state.songPlaying.music_url}`));
		RNAudioStreamer.play();
	}

	componentDidMount() {
		let params = this.behaviourParams('play');
		store(params);
	    PushNotification.cancelAllLocalNotifications();
	}

	behaviourParams(activity, contentId, artistId) {
		const { songPlaying, user } = this.state;
		return {
			type		: 'song',
			activity	: activity,
			content		: (contentId) ? contentId : songPlaying.music_id,
			artist		: (artistId) ? artistId : songPlaying.artist_id,
			user		: user
		}
	}

	componentWillUnmount() {
		const { songPlaying } = this.state;
		// listener = false;
		PushNotification.localNotification({
		    /* Android Only Properties */
		    id: '0', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
		    ticker: "My Notification Ticker", // (optional)
		    autoCancel: true, // (optional) default: true
		    largeIcon: "ic_launcher", // (optional) default: "ic_launcher"
		    smallIcon: "ic_notification", // (optional) default: "ic_notification" with fallback for "ic_launcher"
		    bigText: `${songPlaying.artist_name} - ${songPlaying.music_title}`, // (optional) default: "message" prop
		    subText: "GTunes Music Player", // (optional) default: none
		    color: "green", // (optional) default: system default
		    vibrate: false, // (optional) default: true
		    tag: 'some_tag', // (optional) add tag to message
		    group: "group", // (optional) add group to message
		    ongoing: false, // (optional) set whether this is an "ongoing" notification

		    /* iOS and Android properties */
		    title: "Playing Song", // (optional, for iOS this is only used in apple watch, the title will be the app name on other iOS devices)
		    message: `${songPlaying.artist_name} - ${songPlaying.music_title}`, // (required)
		    playSound: false, // (optional) default: true
		    actions: '["Play", "Pause", "Stop"]',  // (Android only) See the doc for notification actions to know more
		});
	}

	_statusChanged(status) {
		if(listener) {
			if(status == 'PLAYING' || status == 'BUFFERING')
			  this.setState({status: 1});
			else if(status == 'PAUSED')
			  this.setState({status: 2});
			else // NOT PLAYING
			  this.setState({status: 3});
		}
	}

	renderPlayPause() {
		if(this.state.status == 3) { // STOPPED / FINISHED
			return (
				<Entypo
					onPress={() => this.play()}
					name= 'controller-play'
					size={18}
					style={style.playIcon}
				/>
			);
		}

		if(this.state.status == 2) { // PAUSED
			return (
				<Entypo
					onPress={() => this.play()}
					name= 'controller-play'
					size={18}
					style={style.playIcon}
				/>
			);
		}

		return ( // PLAYING
			<Entypo
				onPress={() => this.pause()}
				name= 'controller-paus'
				size={18}
				style={style.playIcon}
			/>
		);
	}

	play(musicId = null, artistId = null) {
		RNAudioStreamer.play();
		this.setState({status: 1});
		let params = this.behaviourParams('play', musicId, artistId);
		store(params);
	}

	pause() {
		RNAudioStreamer.pause();
		this.setState({status: 2});
		let params = this.behaviourParams('stop');
		store(params);
	}

	otherSong() {
		const { state } = this.props.navigation;
		let all = state.params.all;
		let current = state.params.current;


		if(_.size(all) == 1) {
			alert('Semua lagu sudah dimainkan. Silahkan pilih artis / lain');
		} else {
			let shuff = _.shuffle(all);
			let other = _.head(shuff);
			RNAudioStreamer.setUrl(encodeURI(`${IMAGE_HOST_URL}/${other.music_url}`));
			this.setState({songPlaying: other});
			this.play(other.music_id, other.artist_id);
		}
	}

	render() {
		return (
			<View style={style.container}>
				<View style={style.artistContainer}>
					<Text style={style.artist}>{this.state.songPlaying.artist_name}</Text>
				</View>
				<View style={style.imageContainer}>
					<Image 
						style={style.image}
						source={{uri:`${IMAGE_HOST_URL}/${this.state.songPlaying.music_artwork}`}}
					/>
				</View>
				<View style={style.detail}>
					<Text style={style.title}>{this.state.songPlaying.music_title}</Text>
				</View>
				<View style={style.controlGroup}>
					<Entypo
						name= 'controller-jump-to-start'
						size={18}
						style={style.songIcon}
						onPress={() => this.otherSong()}
					/>

					{this.renderPlayPause()}

					<Entypo
						name= 'controller-next'
						size={18}
						style={style.songIcon}
						onPress={() => this.otherSong()}
					/>
				</View>
			</View>
		);
	}
}

export default MusicPlayerScreen;